name = input("what is ur name: ")
klass = input("In which class do u read: ")
city = input("In which city dou u live: ")
print("your name is",name)
print("your name is",klass)
print("your name is",city)